### ISSUE TITLE
Display a card on hover

### ISSUE THREAD

**Issue by Soreine** [Soreine/hyper-gwent#1]
Like GwentDB, but on any authorised page.

Questions:

- Use gwentapi or use gwentdb ?
- Cross-origin and XSS
- Avoid CSS conflicts
- How to style the text in the document? Preserve existing links?

**Comment by Zhouzi** [comment]
#8 implements the basics of this issue (displaying a tooltip). The request to the API (if needed) will be implemented later, per #15
