### ISSUE TITLE
Add support for aliases

### ISSUE THREAD

**Issue by Zhouzi** [Soreine/hyper-gwent#13]
The search algorithm should also be able to match aliases. For example, Villentretenmerth is sometimes abbreviated "Vil", Yennefer called "Yen".

**Comment by Zhouzi** [comment]
Actually, the search algorithm will probably match abbreviations so I'm wondering if there are really cases where we'll want to add aliases. If not, this issue can be ignored and closed.

**Comment by Soreine** [comment]
Starting with #22 we will able to add multiple entries in the dictionary for the same card (that's what is done for plurals).

**Comment by Tri125** [comment]
Look up https://github.com/PabloSzx/Gwent-Cards/blob/master/src/data/nicknames.json maybe you could ask Pablo if you could use his alias file.

**Comment by Zhouzi** [comment]
Thank you very much @Tri125, that is indeed an interesting list!

**Comment by Zhouzi** [comment]
Implemented in #31
