### ISSUE TITLE
How to efficiently detect card names inside an HTML document

### ISSUE THREAD

**Issue by Soreine** [Soreine/hyper-gwent#3]
- Restrict the extension to a list of enabled websites
- Use appropriate data structure for the card name dictionary (see variations of https://en.wikipedia.org/wiki/Trie)
- Case insensitive ? Typo insensitive ? 
- Restrict algorithm on hovering paragraphs of text ?

**Comment by Zhouzi** [comment]
This issue is now split into separate parts.
