### ISSUE TITLE
Prepare extension announcement

### ISSUE THREAD

**Issue by Soreine** [Soreine/hyper-gwent#34]
We should post about the extension on Reddit before the next patch. If no one's interested now, we can always post again about it after the new patch release, with the argument that people should be up to date with latest card changes (and new cards).

TODO:

- [x] Add our contact (email, reddit username, anything) on the homepage
- [ ] Move this project to a free organization HyperGwent (better branding, friendlier for potential collaborators, better github page domain)

**Comment by Zhouzi** [comment]
I don't think creating an organization would do any good. It'd probably have just 1 repository. You deserve you get full credit for it and putting real people behind Gwent community projects makes it easier for us to connect ❤️

**Comment by Zhouzi** [comment]
In my opinion, the extension is now ready to be shared 🎉
