### ISSUE TITLE
Add support for Firefox

### ISSUE THREAD

**Issue by Zhouzi** [Soreine/hyper-gwent#38]
Apparently, it'd be much appreciated as a Firefox extension as well. The only blocker is our usage of the shadow DOM. Since we're just using it to isolate our CSS from the page's we could easily get rid of it. We'd need to reset the styles for each element but we can probably get it right.

So, to publish it as a Firefox extension we need to:

1. Use a fallback when shadow DOM is not supported
    * [ ] Detect shadow DOM support
    * [ ] Use inline styles instead of `<style />` with CSS classes (maybe there's a webpack loader for that)
    * [ ] Create an exhaustive CSS reset and apply it to every single elements
2. Adapt the current configuration to Firefox

I don't know much about Firefox extensions but since they decided to follow the manifest 2.0, it shouldn't be too hard.

**Comment by Soreine** [comment]
I tried enabling Shadow DOM in Firefox, but too much functions are missing (like `attachShadow`)

**Comment by Zhouzi** [comment]
> on a related topic, I was thinking we could just have one tooltip wrapper, that we reuse for every tooltip

Actually, once we're able to reset styles for a container it wouldn't be harder to reset styles for all of them. Using 1 container VS several containers is more a matter of performance I think.

**Comment by Vexslasher** [comment]
I don't know if this is what you actually need or not but I found [this code](http://jsfiddle.net/HAVJH/3/) that deals with tool tips not sure if it has anything to do with extensions or not though but it does work with Firefox.

**Comment by Zhouzi** [comment]
Thank you very much @Vexslasher 👍 

Actually, I think we got the tooltip quite right and it should work across all modern browsers. The current blocker for Firefox is our use of a technology that it does not support yet. Nothing too bad though, we'll find a way to fix that 😄

**Comment by warang580** [comment]
There is a polyfill to use shadow DOM on Firefox:

https://developers.google.com/web/fundamentals/getting-started/primers/shadowdom?hl=en#support

**Comment by Zhouzi** [comment]
Now, that's good news! Thank you @warang580 will give it a try.
