### ISSUE TITLE
Refactor extension to have all data externalised

### ISSUE THREAD

**Issue by Soreine** [Soreine/hyper-gwent#44]
We should not have to publish a new version of the extension in order to be up-to-date with the latest cards info.

**Comment by Soreine** [comment]
@Zhouzi do you think we could make a static API, using gh-pages ? Or another free service. We just need to serve the equivalent of the current  `cards.json` as one endpoint, and just another endpoint to serve the latest version. The extension would check compare its version to the latest one. If it is late, it would download the new cards JSON, and store it in the browser/extension storage idk, and use that afterward.

**Comment by Soreine** [comment]
All we have to do to maintain the API is to update the served data in the static API

**Comment by Zhouzi** [comment]
I was thinking about a lazier solution but yours seems like a good balance between performance and required maintenance. I might experiment with a SaaS (perhaps zeit.co) to have some kind of CRON updating the cards on a regular basis, that way we don't have to think about it anymore.

**Comment by Soreine** [comment]
Done by #54
